project_id = "qlrfbaantfrqzyrunoau"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[graphql]
enabled = true
port = 54329
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[inbound_smtp]
enabled = false

[db]
port = 54322
shadow_port = 54320
major_version = 15

[realtime]
enabled = true
ip_version = 4
port = 54323
max_header_length = 4096

[studio]
enabled = true
port = 54323
api_url = "http://127.0.0.1:54321"
openai_api_key = "env(OPENAI_API_KEY)"

[auth]
enabled = true
port = 54324
site_url = "http://127.0.0.1:3000"
additional_redirect_urls = ["https://127.0.0.1:3000"]
jwt_expiry = 3600
refresh_token_rotation_enabled = true
refresh_token_reuse_interval = 10
enable_manual_linking = false

[auth.email]
enable_signup = true
double_confirm_changes = true
enable_confirmations = false
template_path = "./supabase/templates"

[auth.sms]
enable_signup = true
enable_confirmations = false
template_path = "./supabase/templates"

[edge_runtime]
enabled = true
port = 54325
inspector_port = 54326

[analytics]
enabled = false
port = 54327
vector_port = 54328
backend = "postgres"

[functions.gmail-oauth]
verify_jwt = false

[functions.gmail-processor]
verify_jwt = false

[functions.fakturownia-api]
verify_jwt = false

[functions.imap-connect]
verify_jwt = false